version: '3'

services:
  db:
    image: mariadb:10.6
    container_name: dbmanager
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: admin
      MARIADB_DATABASE: dbsenati
      MARIADB_PASSWORD: 123456
    volumes:
      - db_data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
  
  phpmyadmin:
    image: phpmyadmin:5.2.0-apache
    container_name: phpmyadminlocal
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_ARBITRARY: 1
  
  web:
    build: .
    depends_on:
      - db
    ports:
      - 3030:80

volumes:
  db_data:
