version: '3'

services:
  db:
    image: mariadb:10.6
    container_name: ${DB_HOST}
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: ${DB_USER}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_PASSWORD: ${DB_PASS}
    volumes:
      - db_data:/var/lib/mysql
      - ./db/backup.sql:/docker-entrypoint-initdb.d/backup.sql
  
  web:
    build: .
    depends_on:
      - db
    ports:
      - 3030:80
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_NAME: ${DB_NAME}
      DB_PASS: ${DB_PASS}

volumes:
  db_data: